### PR TITLE
Add command for creating a presentation definition

### LINKED ISSUE #123: Resolve `rustup default stable` DX
Right now developer's have to run `rustup default stable` to add underlying rust-related CLI dependencies, whereafter that's cached inside of `.hermit/`. But this is less than ideal; hermit should bring these matters out of the box.

```
rs on  kendall/justfile [$] via 🦀 1.77.2
➜ rm -rf .hermit

rs on  kendall/justfile [$] via 🦀  took 20.1s
➜ cargo
error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.

rs on  kendall/justfile [$] via 🦀
➜ rustup default stable
info: syncing channel updates for 'stable-aarch64-apple-darwin'
info: latest update on 2024-04-09, rust version 1.77.2 (25ef9e3d8 2024-04-09)
info: downloading component 'cargo'
  6.2 MiB /   6.2 MiB (100 %)   6.0 MiB/s in  1s ETA:  0s
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 14.9 MiB /  14.9 MiB (100 %)   4.8 MiB/s in  3s ETA:  0s
info: downloading component 'rust-std'
 22.9 MiB /  22.9 MiB (100 %)   8.2 MiB/s in  2s ETA:  0s
info: downloading component 'rustc'
 54.1 MiB /  54.1 MiB (100 %)   8.4 MiB/s in  6s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
 14.9 MiB /  14.9 MiB (100 %)   3.5 MiB/s in  2s ETA:  0s
info: installing component 'rust-std'
 22.9 MiB /  22.9 MiB (100 %)  19.7 MiB/s in  1s ETA:  0s
info: installing component 'rustc'
 54.1 MiB /  54.1 MiB (100 %)  20.3 MiB/s in  2s ETA:  0s
info: installing component 'rustfmt'
info: default toolchain set to 'stable-aarch64-apple-darwin'

  stable-aarch64-apple-darwin installed - rustc 1.77.2 (25ef9e3d8 2024-04-09)


rs on  kendall/justfile [$] via 🦀 1.77.2 took 26.9s
➜ cargo
Rust's package manager

Usage: cargo [+toolchain] [OPTIONS] [COMMAND]
       cargo [+toolchain] [OPTIONS] -Zscript <MANIFEST_RS> [ARGS]...
```

### LINKED ISSUE #328: (Feature): Add command and functionality to create a presentation definition
## 🚀 Goal
Add a new command to the Web5 Rust CLI that allows users to create a presentation definition.

## 🔑 Tasks
- [ ] Create a new command for creating presentation definitions (e.g., `web5 pd create`)
- [ ] Implement the logic to generate a basic presentation definition structure
- [ ] Add options to specify input descriptors, format, etc.
- [ ] Implement validation to ensure created presentation definitions are valid
- [ ] Add appropriate documentation for the new command
- [ ] Provide examples of how to use the command with various options
- [ ] Write tests to ensure the feature works correctly
- [ ] Update the CLI's help information to include the new command
- [ ] For more complex structures or large Presentation Definitions, consider adding an option to read from a JSON file.

# web5 pd create Command Structure

### Basic Usage
```
web5 pd create <id> [options]
```

### Options
- `--name <name>`: Set the name of the Presentation Definition
- `--purpose <purpose>`: Set the purpose of the Presentation Definition
- `--input-descriptor <descriptor>`: Add an input descriptor (can be used multiple times)
  - Format: `id:name:purpose`
- `--field <field>`: Add a field to the last input descriptor (can be used multiple times)
  - Format: `id:name:path:purpose:optional:predicate`
  - `path` should be a comma-separated list of strings
  - `optional` should be "true" or "false"
  - `predicate` should be "required" or "preferred"
- `--filter <filter>`: Add a filter to the last field (can be used multiple times)
  - Format: `type:pattern:const_value`

1. Create a basic Presentation Definition:
```
web5 pd create my-pd-1 --name "Basic PD" --purpose "Verification"
```

2. Create a Presentation Definition with an input descriptor:
```
web5 pd create my-pd-2 --name "PD with Descriptor" --purpose "Identity Check" --input-descriptor "input-1:Personal Info:Verify personal information"
```

3. Create a complex Presentation Definition:
```
web5 pd create my-pd-3 \
  --name "Complex PD" \
  --purpose "Comprehensive Verification" \
  --input-descriptor "input-1:Personal Info:Verify personal information" \
  --field "field-1:Name:$.credentialSubject.name:Verify name:false:required" \
  --filter "string:^[A-Za-z ]+$" \
  --field "field-2:Age:$.credentialSubject.age:Verify age:true:preferred" \
  --filter "number:^[0-9]+$" \
  --input-descriptor "input-2:Address:Verify address" \
  --field "field-3:Street:$.credentialSubject.address.street:Verify street:false:required"
```

## 🌟 Resources
- [Current Web5 Rust CLI Documentation](https://github.com/TBD54566975/web5-rs/tree/main/crates/web5_cli)
- [Web5 Rust CLI Source Code](https://github.com/TBD54566975/web5-rs/tree/main/crates/web5_cli/src)
- [Web5 documentation on Presentation Definitions](https://developer.tbd.website/docs/web5/verifiable-credentials/presentation-definition)
- [Web5 Rust API Design on Presentation Definition](https://github.com/TBD54566975/web5-rs/blob/main/docs/API_DESIGN.md#presentationdefinition)
- [Rust CLI Argument Parsing Best Practices](https://rust-cli.github.io/book/tutorials/cli-args.html)
- [Web5 CLI built in Go for reference](https://github.com/TBD54566975/web5-go/tree/main/cmd/web5)

## ⚡  Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Update the documentation as described in the tasks
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## 💭 Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.
Happy coding! 🎉

### PR DESCRIPTION
**Pull request by w3irdrobot**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds this the `web5 pd create` command for generating presentation definitions. 

## Related Tickets & Documents

Resolves #328 

## Added code snippets?
- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [x 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x] 📓 general documentation
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

No

## [optional] What gif best describes this PR or how it makes you feel?

image

### CODE REVIEW

**Comment by angiejones** [comment]
thanks so much! we'll review soon 🙏🏾

**Comment by blackgirlbytes** [comment]
yay thank you @w3irdrobot!!! I think @bnonni was mentioning to me that you're familiar with Rust but new to the PEX game. appreciate the contribution!

**Comment by nitro-neal** [comment]
I have an ask, for these complex objects lets have an optional json input param so we can just copy paste a pd input into the command line

**Comment by taniashiba** [comment]
Hey @nitro-neal @KendallWeihe - If there is nothing else required to close this PR as the task describes, please review, merge and close this PR and attach the `hacktoberfest-accepted` so that this contribution can count for Hacktoberfest. Hacktoberfest ends this week 🙏 Thank you so much!

**Comment by blackgirlbytes** [comment]
Oh yeah my intention with this issue was to just enable people to be able to create a PD via the CLI @nitro-neal @w3irdrobot

**Review by KendallWeihe — APPROVED** [review]
really great work here, thank you @w3irdrobot!

**Pull request merged**
