### PR TITLE
Generate X25519 keys

### PR DESCRIPTION
**Pull request by diehuxx**
Follow up from https://github.com/TBD54566975/web5-rs/pull/299

### CODE REVIEW

**Comment by KendallWeihe** [comment]
I guess since X25519 isn't a signature alg then it shouldn't be under the DSA namespace, yeah?

**Comment by KendallWeihe** [comment]
we should remove `X25519Signer` and `X25519Verifier` from the APID too yeah?

**Comment by diehuxx** [comment]
Makes sense to me. Any preference on namespace?

**Comment by KendallWeihe** [comment]
> Any preference on namespace

It sounds like this is about key exchange, right? So idk maybe `key_exchange`? or else maybe just in the root crypto

**Comment by decentralgabe** [comment]
[key exchange](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/x25519/) is common terminology

**Review by KendallWeihe — APPROVED** [review]

**Pull request merged**
