### PR TITLE
Add ability to pass in additional-properties in vc create

### LINKED ISSUE #123: Resolve `rustup default stable` DX
Right now developer's have to run `rustup default stable` to add underlying rust-related CLI dependencies, whereafter that's cached inside of `.hermit/`. But this is less than ideal; hermit should bring these matters out of the box.

```
rs on  kendall/justfile [$] via 🦀 1.77.2
➜ rm -rf .hermit

rs on  kendall/justfile [$] via 🦀  took 20.1s
➜ cargo
error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.

rs on  kendall/justfile [$] via 🦀
➜ rustup default stable
info: syncing channel updates for 'stable-aarch64-apple-darwin'
info: latest update on 2024-04-09, rust version 1.77.2 (25ef9e3d8 2024-04-09)
info: downloading component 'cargo'
  6.2 MiB /   6.2 MiB (100 %)   6.0 MiB/s in  1s ETA:  0s
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 14.9 MiB /  14.9 MiB (100 %)   4.8 MiB/s in  3s ETA:  0s
info: downloading component 'rust-std'
 22.9 MiB /  22.9 MiB (100 %)   8.2 MiB/s in  2s ETA:  0s
info: downloading component 'rustc'
 54.1 MiB /  54.1 MiB (100 %)   8.4 MiB/s in  6s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
 14.9 MiB /  14.9 MiB (100 %)   3.5 MiB/s in  2s ETA:  0s
info: installing component 'rust-std'
 22.9 MiB /  22.9 MiB (100 %)  19.7 MiB/s in  1s ETA:  0s
info: installing component 'rustc'
 54.1 MiB /  54.1 MiB (100 %)  20.3 MiB/s in  2s ETA:  0s
info: installing component 'rustfmt'
info: default toolchain set to 'stable-aarch64-apple-darwin'

  stable-aarch64-apple-darwin installed - rustc 1.77.2 (25ef9e3d8 2024-04-09)


rs on  kendall/justfile [$] via 🦀 1.77.2 took 26.9s
➜ cargo
Rust's package manager

Usage: cargo [+toolchain] [OPTIONS] [COMMAND]
       cargo [+toolchain] [OPTIONS] -Zscript <MANIFEST_RS> [ARGS]...
```

### LINKED ISSUE #326: (Feature): Add ability to pass in additional-properties in Web5 CLI to `web5 vc create`
## 🚀 Goal
Enhance the `web5 vc create` command to allow users to pass in additional properties when creating a Verifiable Credential.

## 🔑 Tasks
- [ ] Modify the `web5 vc create` command to accept additional properties
Example below:
```bash
web5 vc create rizel \
  --portable-did $PORTABLE_DID \
  --issuer "did:dht:pe45oj88hq9zza3cjd41r5rej9ekfg9bq7k4jjeaw889t78jesko" \
  --expiration-date "2025-12-31T23:59:59Z" \
  --additional-property "role:engineer" \
  --additional-property "clearance:level5"
```
- [ ] Determine the best format for passing additional properties (e.g., JSON string, key-value pairs)
- [ ] Implement the logic to incorporate these additional properties into the created VC
- [ ] Add appropriate error handling for invalid additional properties
- [ ] Update the CLI documentation to explain how to use this new feature
- [ ] Add examples demonstrating the use of additional properties
- [ ] Write tests to ensure the feature works as expected

## 🌟 Resources
- [Current Web5 Rust CLI Documentation](https://github.com/TBD54566975/web5-rs/tree/main/crates/web5_cli)
- [Web5 documentation on Creating VC](https://developer.tbd.website/docs/web5/verifiable-credentials/vc-issuance)
- [Verifiable Credentials Data Model](https://www.w3.org/TR/vc-data-model/)
- [Web5 CLI built in Go for reference](https://github.com/TBD54566975/web5-go/tree/main/cmd/web5)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Implement the feature as described in the tasks
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## 💭 Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.
Happy coding! 🎉

### PR DESCRIPTION
**Pull request by w3irdrobot**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds ability to pass in additional-properties in `vc create`.

I changed the command's method to take ownership of `self` since it simplified my handling of the values being passed in. This change required updating of a few other parts of the code to act on the values directly instead of through references. 

## Related Tickets & Documents

Resolves #326 

## Added code snippets?
- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x] 📓 general documentation
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

No

## [optional] What gif best describes this PR or how it makes you feel?

image

### CODE REVIEW

**Comment by blackgirlbytes** [comment]
let's gooo

**Review by nitro-neal — APPROVED** [review]
can you post some example output?

**Comment by taniashiba** [comment]
Following up on this - @nitro-neal @KendallWeihe - is there anything else needed here to close out this PR? Given that this is the final week of Hacktoberfest, I want to make sure our contributors get their PRs accepted, and contributions count ahead of that deadline! Thank you so much. 🙏

**Review by KendallWeihe — APPROVED** [review]
well done!

**Comment by blackgirlbytes** [comment]
oh wait..could we resolve the merge conflicts? @w3irdrobot so that we can get this merged.

**Pull request merged**
